### ISSUE TITLE
"default_path" sfz directive is not honored.

### ISSUE THREAD

**Issue by Fak3** [kfoltman/calfbox#2]
If sfz file has "default_path" control directive, sampler example will produce no sound. 
(this issue especially applies to cakewalk samples pack avilable at https://www.digitalsoundfactory.com/e-mu-proteus-pack )

How to reproduce:
Given sfz file content:

```
<control>
default_path=Virtuoso Samples\
...
<region> sample=AltoFlutepS1G#1.wav
...
```

And given all samples reside in "Virtuoso Samples" subdirectory. 
Modify sampler_api_example2.py, changing filepath to this new file.
Run sampler_api_example2.py, and notice that no sound is produced.

If you modify sfz file, extending sample paths with subdirectory, sampler_api_example2.py will work properly:

```
sample=Virtuoso Samples\AltoFlutepS1G#1.wav 
```

**Comment by kfoltman** [comment]
It's an SFZv2 opcode, and I generally didn't have many SFZv2 opcodes implemented in 2015 :) However, I've added it now, together with a small number of other SFZv2 features, like #define, #include, and the new sections - master and global.
