### ISSUE TITLE
Howto use standalone calfbox with a SFZ

### ISSUE THREAD

**Issue by trebmuh** [kfoltman/calfbox#4]
Hi.

I'm starting looking at calfbox for reading/using my SFZ file but I can't find any information on the web about how to use it. Could you please tell me how to do so or, alternatively, give me a URL pointer where I can find information about this?

Thanks.

**Comment by diovudau** [comment]
I am sorry to inform you that the binary executable variant is not maintained and untested at the moment. It should not be used. Calfbox can be considered a Python module for all intents and purposes.

**Comment by trebmuh** [comment]
@diovudau thanks for the info.
Is https://github.com/diovudau/Fluajho/ able (or intended at some later point) to work with SFZ?

**Comment by kfoltman** [comment]
The SFZ functionality in Calfbox can be used, theoretically, but it's all rather poorly documented and not tested much, and there are bugs and some SFZ features are not supported (there's almost no support for v2 features). There is not enough good quality, free SFZ sound banks around to justify putting more effort into it.

For use of the SFZ files in Python module, check out sample_api_example2.py.
For a config for standalone use, check out cboxrc-example - I'll add some actual documentation at some point, if there is enough interest.

This whole project has been more of my personal research/experimentation thing, and has been planned for live music performances (which I no longer do), so things are, well, the way they are.
